export interface Pet {
  id: number;
  name: string;
  species: 'dog' | 'cat' | 'rabbit' | 'bird';
  breed: string;
  age: number;
  gender: 'male' | 'female';
  description: string;
  emoji: string;
  bgGradient: string;
  location: string;
  traits: string[];
}

export const pets: Pet[] = [
  {
    id: 1,
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 3,
    gender: 'male',
    description: 'A playful and loving golden retriever who adores fetch and long walks in the park. Buddy gets along with everyone!',
    emoji: '🐕',
    bgGradient: 'from-yellow-200 to-amber-300',
    location: 'San Francisco, CA',
    traits: ['Playful', 'Friendly', 'Good with kids'],
  },
  {
    id: 2,
    name: 'Luna',
    species: 'cat',
    breed: 'Siamese',
    age: 2,
    gender: 'female',
    description: "Luna is an elegant Siamese who loves to chat and curl up on laps. She's curious, social, and endlessly entertaining.",
    emoji: '🐈',
    bgGradient: 'from-blue-200 to-indigo-300',
    location: 'Portland, OR',
    traits: ['Talkative', 'Affectionate', 'Indoor only'],
  },
  {
    id: 3,
    name: 'Max',
    species: 'dog',
    breed: 'German Shepherd',
    age: 4,
    gender: 'male',
    description: "Max is a loyal and intelligent German Shepherd. He's fully trained, loves outdoor adventures, and is great with families.",
    emoji: '🦮',
    bgGradient: 'from-orange-200 to-red-300',
    location: 'Austin, TX',
    traits: ['Loyal', 'Trained', 'Active'],
  },
  {
    id: 4,
    name: 'Bella',
    species: 'cat',
    breed: 'Ragdoll',
    age: 1,
    gender: 'female',
    description: "Bella is a fluffy Ragdoll kitten who melts in your arms. She's calm, gentle, and perfect for a quiet home.",
    emoji: '😺',
    bgGradient: 'from-pink-200 to-rose-300',
    location: 'Seattle, WA',
    traits: ['Gentle', 'Fluffy', 'Quiet'],
  },
  {
    id: 5,
    name: 'Charlie',
    species: 'dog',
    breed: 'Beagle',
    age: 5,
    gender: 'male',
    description: 'Charlie is a nose-to-the-ground adventurer with a heart of gold. He loves sniffing out fun and cuddling at the end of the day.',
    emoji: '🐶',
    bgGradient: 'from-amber-200 to-orange-300',
    location: 'Chicago, IL',
    traits: ['Curious', 'Affectionate', 'Energetic'],
  },
  {
    id: 6,
    name: 'Cleo',
    species: 'rabbit',
    breed: 'Holland Lop',
    age: 2,
    gender: 'female',
    description: 'Cleo is a floppy-eared Holland Lop who loves binkying around and munching on fresh veggies. Super gentle and social!',
    emoji: '🐰',
    bgGradient: 'from-purple-200 to-violet-300',
    location: 'Denver, CO',
    traits: ['Gentle', 'Social', 'Litter trained'],
  },
  {
    id: 7,
    name: 'Rocky',
    species: 'dog',
    breed: 'Labrador Retriever',
    age: 2,
    gender: 'male',
    description: 'Rocky is an exuberant Lab who lives life at full speed. He loves swimming, fetch, and absolutely everyone he meets.',
    emoji: '🐾',
    bgGradient: 'from-teal-200 to-cyan-300',
    location: 'Miami, FL',
    traits: ['Energetic', 'Loves water', 'Social'],
  },
  {
    id: 8,
    name: 'Mochi',
    species: 'dog',
    breed: 'Shiba Inu',
    age: 3,
    gender: 'female',
    description: "Mochi is a dignified and fox-like Shiba who does things on her own terms. Independent yet loyal, she's a true character.",
    emoji: '🦊',
    bgGradient: 'from-red-200 to-orange-300',
    location: 'New York, NY',
    traits: ['Independent', 'Clean', 'Alert'],
  },
  {
    id: 9,
    name: 'Oscar',
    species: 'bird',
    breed: 'Cockatiel',
    age: 4,
    gender: 'male',
    description: 'Oscar is a cheerful cockatiel who whistles tunes, bobs along to music, and loves sitting on shoulders. Never a dull moment!',
    emoji: '🦜',
    bgGradient: 'from-green-200 to-emerald-300',
    location: 'Nashville, TN',
    traits: ['Vocal', 'Playful', 'Tame'],
  },
  {
    id: 10,
    name: 'Daisy',
    species: 'dog',
    breed: 'Corgi',
    age: 2,
    gender: 'female',
    description: 'Daisy is a short-legged, big-hearted Corgi who thinks she can herd everything. Clever, sassy, and utterly adorable.',
    emoji: '🐕‍🦺',
    bgGradient: 'from-lime-200 to-yellow-300',
    location: 'Boston, MA',
    traits: ['Smart', 'Herding instinct', 'Fun-loving'],
  },
];
